### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by GoldElysium** [GoldElysium/hef-website#250]
## Tasks

- [ ] Rename `src/ui` to `src/components` and properly separate components
- [x] Update branding
- [ ] Make the site accessible
- [ ] Improve user experience
- [ ] Set cache tags for Next.js
- [ ] Add [ESLint plugin for Tailwind CSS](https://www.npmjs.com/package/eslint-plugin-tailwindcss)
- [ ] Apply new design to existing pages
- [ ] Move project submissions to separate page (see #79)
	- [ ] Filtering and return to infinite scroll (using Tanstack Virtualizer and Million)
	- [ ] Alternative: use [content-visibility](https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility) to lessen the load on the user agent (experimental atm)
- [ ] Projects page filtering (see #55)
- [ ] Tripetto forms runner
- [ ] Talent specific page theming
	- [x] Design
	- [ ] Website implementation
- [ ] Add components to Storybook
- [ ] Dynamic OpenGraph images with more information, using [`@vercel/og`](https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation)
- [ ] Implement [ActivityPub](https://www.w3.org/TR/activitypub) to post projects to the Fediverse?

Also see HoloENFans/hef-website-cms#196
